"""Package theorem diagnostics as an immutable manifest and checksum ledger.

The full generated artifact tree can be large.  CI already publishes the
aggregate provenance and coverage reports separately, so this packager records
all generated bytes without duplicating the payload.  The resulting package is
small, deterministic, path-relative, and sufficient to verify a retained tree.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from collections import Counter
from pathlib import Path
from typing import Iterable


SCHEMA_VERSION = "1.0"
CLAIM_BOUNDARY = (
    "byte inventory and checksums for generated finite diagnostics; not formal "
    "proof, physical geometry, or empirical validation"
)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _canonical_json_bytes(value: object) -> bytes:
    return json.dumps(
        value,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")


def _iter_files(root: Path) -> Iterable[Path]:
    for path in sorted(root.rglob("*")):
        if path.is_symlink():
            raise RuntimeError(f"symlink is not permitted in diagnostic tree: {path}")
        if path.is_file():
            yield path


def package(input_root: Path, output_root: Path) -> dict[str, object]:
    source = input_root.resolve()
    destination = output_root.resolve()
    if not source.is_dir():
        raise RuntimeError(f"diagnostic input root is not a directory: {input_root}")
    if destination == source or source in destination.parents:
        raise RuntimeError("diagnostic output root must be outside the input tree")

    records: list[dict[str, object]] = []
    suffix_counts: Counter[str] = Counter()
    total_bytes = 0
    for path in _iter_files(source):
        relative = path.relative_to(source)
        if relative.is_absolute() or ".." in relative.parts:
            raise RuntimeError(f"unsafe diagnostic relative path: {relative}")
        size = path.stat().st_size
        suffix = path.suffix.lower() or "<none>"
        digest = _sha256(path)
        total_bytes += size
        suffix_counts[suffix] += 1
        records.append(
            {
                "path": relative.as_posix(),
                "sha256": digest,
                "size_bytes": size,
                "suffix": suffix,
            }
        )

    if not records:
        raise RuntimeError("diagnostic input tree contains no files")

    tree_sha256 = hashlib.sha256(_canonical_json_bytes(records)).hexdigest()
    payload: dict[str, object] = {
        "schema_version": SCHEMA_VERSION,
        "input_root_role": "ephemeral_theorem_diagnostic_tree",
        "file_count": len(records),
        "total_bytes": total_bytes,
        "suffix_counts": dict(sorted(suffix_counts.items())),
        "tree_sha256": tree_sha256,
        "paths_are_relative": True,
        "symlinks_permitted": False,
        "payload_files_embedded": False,
        "claim_boundary": CLAIM_BOUNDARY,
        "files": records,
    }

    destination.mkdir(parents=True, exist_ok=True)
    manifest = destination / "theorem_diagnostic_file_manifest.json"
    manifest.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    checksums = destination / "SHA256SUMS"
    checksums.write_text(
        "".join(f"{record['sha256']}  {record['path']}\n" for record in records),
        encoding="utf-8",
    )
    manifest_digest = _sha256(manifest)
    (destination / "theorem_diagnostic_file_manifest.json.sha256").write_text(
        f"{manifest_digest}  theorem_diagnostic_file_manifest.json\n",
        encoding="utf-8",
    )
    (destination / "README.md").write_text(
        "# Theorem diagnostic checksum package\n\n"
        "This package intentionally contains a manifest and checksum ledger, not "
        "a duplicate upload of the complete generated artifact tree.\n\n"
        f"Tree SHA-256: `{tree_sha256}`\n\n"
        f"Claim boundary: {CLAIM_BOUNDARY}.\n",
        encoding="utf-8",
    )
    return payload


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-root", type=Path, required=True)
    parser.add_argument("--output-root", type=Path, required=True)
    args = parser.parse_args()
    report = package(args.input_root, args.output_root)
    print(
        "theorem_diagnostic_package=passed "
        f"files={report['file_count']} bytes={report['total_bytes']} "
        f"tree_sha256={report['tree_sha256']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
