"""Torch-native DTQC inflation and spectral-closure operator for QENN.

The operator is a finite numerical realization of the module's four canonical
A sources, their two additive B diagnostics, and the C-level elastic/Parseval
quasicrystal closure.  It returns a numerical candidate and never promotes a
small residual to a formal existence or attainment claim.
"""

from __future__ import annotations

from dataclasses import dataclass
import math

import torch
from torch import nn

from the_nothingness_effect._runtime.theorem_complex_runtime.types import (
    DomainViolationError,
    NonFiniteValueError,
)

from .contracts import SPEC


DTQC_COMPLEX_IDS = (*SPEC.a_ids, *SPEC.b_ids, SPEC.c_id)


@dataclass(frozen=True)
class DTQCNeuralState:
    """Typed finite DTQC state consumed by QENN."""

    carrier: torch.Tensor
    inflated_state: torch.Tensor
    spectral_measure: torch.Tensor
    support_mask: torch.Tensor
    reconstruction: torch.Tensor
    input_leakage: torch.Tensor
    residuals: dict[str, torch.Tensor]
    complex_ids: tuple[str, ...] = DTQC_COMPLEX_IDS
    closure_status: str = "numerical_candidate"


def fibonacci_word(length: int) -> tuple[int, ...]:
    """Return the finite prefix generated by A->AB, B->A."""

    if not isinstance(length, int) or length < 1:
        raise DomainViolationError("DTQC Fibonacci inflation requires a positive integer length")
    word = (0,)
    while len(word) < length:
        word = tuple(item for symbol in word for item in ((0, 1) if symbol == 0 else (0,)))
    return word[:length]


def _rfft_energy(spectrum: torch.Tensor, sample_count: int) -> torch.Tensor:
    weights = torch.ones(spectrum.shape[-1], dtype=spectrum.real.dtype, device=spectrum.device)
    if sample_count % 2 == 0:
        if weights.numel() > 2:
            weights[1:-1] = 2.0
    elif weights.numel() > 1:
        weights[1:] = 2.0
    return (spectrum.abs().square() * weights).sum(dim=-1)


class DTQCInflationLayer(nn.Module):
    """Pisot/Fibonacci inflation followed by fixed-support spectral closure."""

    def __init__(
        self,
        *,
        pisot_factor: float = (1.0 + math.sqrt(5.0)) / 2.0,
        strength: float = 0.25,
        support_fraction: float = 0.5,
    ) -> None:
        super().__init__()
        if not math.isfinite(pisot_factor) or pisot_factor <= 1.0:
            raise DomainViolationError("DTQC Pisot factor must be finite and greater than one")
        if not math.isfinite(strength) or not 0.0 < strength < 1.0:
            raise DomainViolationError("DTQC inflation strength must lie strictly between zero and one")
        if not math.isfinite(support_fraction) or not 0.0 < support_fraction <= 1.0:
            raise DomainViolationError("DTQC support fraction must lie in (0, 1]")
        self.register_buffer("pisot_factor", torch.tensor(float(pisot_factor)))
        self.register_buffer("strength", torch.tensor(float(strength)))
        self.support_fraction = float(support_fraction)

    def forward(self, value: torch.Tensor, *, elastic_gain: torch.Tensor | None = None) -> DTQCNeuralState:
        if not isinstance(value, torch.Tensor) or value.ndim != 2 or value.shape[-1] < 2:
            raise DomainViolationError("DTQC neural operator requires a rank-two tensor with at least two features")
        if not bool(torch.isfinite(value).all()):
            raise NonFiniteValueError("DTQC neural input contains NaN or infinity")
        feature_count = value.shape[-1]
        dtype = value.dtype
        device = value.device

        symbols = torch.tensor(fibonacci_word(feature_count), dtype=dtype, device=device)
        phi = self.pisot_factor.to(dtype=dtype, device=device)
        amplitudes = torch.where(symbols == 0, torch.ones_like(symbols), torch.ones_like(symbols) / phi)
        centered = amplitudes - amplitudes.mean()
        scale = centered.abs().amax().clamp_min(torch.finfo(dtype).eps)
        phase_clock = torch.cos(2.0 * torch.pi * torch.arange(feature_count, dtype=dtype, device=device) / phi)
        carrier = centered / scale * phase_clock
        profile = 1.0 + self.strength.to(dtype=dtype, device=device) * carrier
        inflated = value * profile

        spectrum = torch.fft.rfft(inflated, dim=-1, norm="ortho")
        carrier_spectrum = torch.fft.rfft(profile, dim=-1, norm="ortho").abs()
        support_count = max(2, math.ceil(carrier_spectrum.numel() * self.support_fraction))
        support_count = min(support_count, carrier_spectrum.numel())
        indices = torch.topk(carrier_spectrum, support_count, sorted=True).indices
        support_mask = torch.zeros_like(carrier_spectrum, dtype=torch.bool).scatter(0, indices, True)
        projected = spectrum * support_mask
        reconstruction = torch.fft.irfft(projected, n=feature_count, dim=-1, norm="ortho")
        reconstructed_spectrum = torch.fft.rfft(reconstruction, dim=-1, norm="ortho")

        denominator = torch.linalg.vector_norm(spectrum).clamp_min(torch.finfo(dtype).eps)
        input_leakage = torch.linalg.vector_norm(spectrum - projected) / denominator
        spectral_residual = torch.linalg.vector_norm(reconstructed_spectrum - projected)
        support_residual = torch.linalg.vector_norm(reconstructed_spectrum * ~support_mask)
        parseval_residual = torch.linalg.vector_norm(
            reconstruction.square().sum(dim=-1) - _rfft_energy(projected, feature_count)
        )

        regenerated = torch.tensor(fibonacci_word(feature_count), dtype=dtype, device=device)
        inflation_residual = torch.linalg.vector_norm(symbols - regenerated)
        locking_residual = torch.linalg.vector_norm(
            phase_clock
            - torch.cos(2.0 * torch.pi * torch.arange(feature_count, dtype=dtype, device=device) / phi)
        )
        if elastic_gain is None:
            elastic_gain = torch.ones((value.shape[0], 1), dtype=dtype, device=device)
        if elastic_gain.shape not in {(value.shape[0], 1), value.shape}:
            raise DomainViolationError("DTQC elastic gain must be per-sample or aligned with the input field")
        if not bool(torch.isfinite(elastic_gain).all()) or bool((elastic_gain <= 0).any()):
            raise NonFiniteValueError("DTQC elastic gain must be finite and strictly positive")
        transported = projected * elastic_gain[..., :1]
        transport_residual = torch.linalg.vector_norm(transported * ~support_mask)
        diophantine_parseval = torch.sqrt(parseval_residual.square() + locking_residual.square())
        spatial_closure = torch.sqrt(
            spectral_residual.square()
            + support_residual.square()
            + parseval_residual.square()
            + inflation_residual.square()
            + transport_residual.square()
        )

        residuals = {
            SPEC.a_ids[0]: spectral_residual,
            SPEC.a_ids[1]: support_residual,
            SPEC.a_ids[2]: parseval_residual,
            SPEC.a_ids[3]: inflation_residual,
            SPEC.b_ids[0]: transport_residual,
            SPEC.b_ids[1]: diophantine_parseval,
            SPEC.c_id: spatial_closure,
        }
        if not all(bool(torch.isfinite(item)) for item in residuals.values()):
            raise NonFiniteValueError("DTQC neural residual contains NaN or infinity")
        return DTQCNeuralState(
            carrier,
            inflated,
            projected,
            support_mask,
            reconstruction,
            input_leakage,
            residuals,
        )
